"""init migration

Revision ID: 996a49c49d12
Revises: 
Create Date: 2020-03-21 13:55:27.744544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '996a49c49d12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    op.drop_table('device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('device_name', name='device_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sensor_data',
    sa.Column('sensor_data_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('roll', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pitch', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yaw', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_x', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_y', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acc_z', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['device.device_name'], name='sensor_data_device_name_fkey'),
    sa.PrimaryKeyConstraint('sensor_data_id', name='sensor_data_pkey')
    )
    # ### end Alembic commands ###
